### ISSUE TITLE
Error handling when reading source maps

### ISSUE THREAD

**Issue by watson** [rexxars/sourcemap-decorate-callsites#2]
I've noticed a few places where you don't pass on the error to the callback. There might be good reasons for this of course, so please fill me in 😃 

- When reading a source map [returns an error](https://github.com/rexxars/sourcemap-decorate-callsites/blob/01744bab66a199399a88434ba6b8b6315d086071/lib/index.js#L94), you try to parse the source map anyway. Shouldn't you simply call the callback with the error object?
- When consuming the source map [throws an error](https://github.com/rexxars/sourcemap-decorate-callsites/blob/01744bab66a199399a88434ba6b8b6315d086071/lib/index.js#L101), you swallow it and return the consumer anyway. Shouldn't you simply call the callback with the error object?

**Comment by watson** [comment]
I have the same question for the sync part of the API. It should probably throw the error in that case.

**Comment by rexxars** [comment]
These seem like errors, indeed. I'll take a look while I'm refactoring.

**Comment by rexxars** [comment]
The silent suppression of errors is now removed in 4ffccbffe7b90e12e047d45346a0961e321861a6, which passes the decision on how to handle errors on to the consuming module.
