### ISSUE TITLE
Separate sync and async API?

### ISSUE THREAD

**Issue by watson** [rexxars/sourcemap-decorate-callsites#3]
When having both a sync and an async API, it's normal in Node.js to use two different functions, where the sync version have the word `Sync` appended to the name.

This module uses the presence of the callback to determine if it should use the sync or the async version, which might be a little weird for people who are used to the other approach.

There's also a potential gotcha with this approach: If the callback is given by a 3rd party and passed directly to this module, if the 3rd party forgets to give the callback this module will switch to sync mode - the result of which would be really hard do debug. This means that users of this module ideally needs to handle that case manually (which most probably will not know to do). If the sync and the async logic were separated into two functions this would not be an issue 😃

**Comment by rexxars** [comment]
True, seems like a better choice. I'll try to refactor.

**Comment by rexxars** [comment]
Synchronous API fully removed in 4ffccbffe7b90e12e047d45346a0961e321861a6.
