### ISSUE TITLE
Make loadSourcemapConsumer into its own module

### ISSUE THREAD

**Issue by watson** [rexxars/sourcemap-decorate-callsites#5]
You should consider making the `loadSourcemapConsumer` function into its own module on npm: https://github.com/rexxars/sourcemap-decorate-callsites/blob/5b9735a156964973a75dc62fd2c7f0c1975458e8/lib/index.js#L35-L77

It's a pretty useful function and a good low-level/standalone function that does a critical part of this modules work 😃

**Comment by watson** [comment]
The module name `load-source-map` is available 😉

**Comment by rexxars** [comment]
Agreed, that seems very reusable. Will refactor.

**Comment by watson** [comment]
The reason why I was looking into this was because I was considering using just that module in Stackman. Because I need to access the consumer object in some way if I want to load the original source code if it's stored in the source map. This would be one way to do it.

**Comment by rexxars** [comment]
[Mostly done](https://github.com/rexxars/load-source-map). I have one API decision that I'm not really sure about, thought I'd get your opinion on it;

If you pass the location of a source file that does not contain a referenced or inline sourcemap, should that result in an error, or simply not give back any source map?

**Comment by watson** [comment]
I think I'd just do as you do now, which as far as I can see is just calling the callback without any arguments if there's no source map.

That makes it easier for the user to differentiate between an actual error (e.g. I/O error or invalid source map) and just that there isn't a source map.

**Comment by rexxars** [comment]
That was my initial thought as well, so I'll go with that. Will bump to 1.0.0, to mark some API stability, and will refactor `sourcemap-decorate-callsites` to use `load-source-map` internally.
